Hw sys and os
LiliiaBgdnv/Python_BI_2022 pull request #12
Opened 2022-12-10 15:17 UTC by LiliiaBgdnv

2022-12-10 21:27 UTC, nvaulin commented on hw_sys_os/README.md
> +![image](https://user-images.githubusercontent.com/109213422/206862131-320b447d-e649-48ad-b195-5f548575ae85.png)
😁👍

2022-12-19 00:14 UTC, krglkvrmn requested changes
![image](https://user-images.githubusercontent.com/48160953/208326962-7c99f76e-c825-4628-afd7-6df0f78ebb0f.png)

2022-12-19 00:14 UTC, krglkvrmn commented on hw_sys_os/ls.py
> +import argparse
?
![image](https://user-images.githubusercontent.com/48160953/208325883-d5515c41-580c-4c93-b979-f65e1c33dcf6.png)

2022-12-19 00:14 UTC, krglkvrmn commented on hw_sys_os/ls.py
> +#!/usr/bin/env python3
Верно

2022-12-19 00:14 UTC, krglkvrmn commented on hw_sys_os/ls.py
> +        raise NotADirectoryError(string)
В данном контексте лучше распечатать какое-то сообщению юзеру и сделать sys.exit(1)

2022-12-19 00:14 UTC, krglkvrmn commented on hw_sys_os/ls.py
> +    list_dir = sorted((f for f in os.listdir() if not f.startswith('.')))
Много повторяющегося кода
```suggestion
dir_contents = os.listdir(args.some_dir) + [".", ".."]
# А дальше отфильтровать в зависимости от `args.all` и распечатать
```

2022-12-19 00:14 UTC, krglkvrmn commented on hw_sys_os/mkdir.py
> +        if not os.path.exists(name, exist_ok=True):
У данной функции нет, такого аргумента, а скрипт падает с ошибкой. Это аргумент makedirs
![image](https://user-images.githubusercontent.com/48160953/208326186-990eba9d-60dd-4cb1-a017-8bfa9c298de3.png)

2022-12-19 00:14 UTC, krglkvrmn commented on hw_sys_os/rm.py
> +args = parser.parse_args()
Лучше делать отступ хотя бы в одну строку от блока с аргументами для лучшей читаемости
```suggestion
parser.add_argument('input', nargs='*')
args = parser.parse_args()

```

2022-12-19 00:14 UTC, krglkvrmn commented on hw_sys_os/wc.py
> +parser.add_argument('-c', '--bytes', action='store_true', help='print the byte counts')
Данная опция не работает в пайпе
![image](https://user-images.githubusercontent.com/48160953/208326572-ca638c91-3523-4146-9036-db9bf8d6898f.png)

2023-01-27 19:12 UTC, merged